apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"python","namespace":"dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"python"}},"template":{"metadata":{"labels":{"app":"python"}},"spec":{"containers":[{"args":["100000"],"command":["sleep"],"image":"python","imagePullPolicy":"Always","name":"python","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"args":["100000"],"command":["sleep"],"image":"python","imagePullPolicy":"Always","name":"python1","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}]}}}}
  creationTimestamp: "2020-11-20T18:19:25Z"
  generation: 9
  name: python
  namespace: dev
  resourceVersion: "394634"
  selfLink: /apis/apps/v1/namespaces/dev/deployments/python
  uid: 496be05d-fb9a-46b1-942e-82803fe37e37
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - args:
        - "100000"
        command:
        - sleep
        image: python
        imagePullPolicy: Always
        name: python
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - "100000"
        command:
        - sleep
        image: python
        imagePullPolicy: Always
        name: python1
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-11-20T18:19:25Z"
    lastUpdateTime: "2021-01-08T08:57:45Z"
    message: ReplicaSet "python-6d457b66bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-01-12T16:27:20Z"
    lastUpdateTime: "2021-01-12T16:27:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
