apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: dev
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - args:
        - "100000"
        command:
        - sleep
        image: python
        imagePullPolicy: Always
        name: python
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - "100000"
        command:
        - sleep
        image: python
        imagePullPolicy: Always
        name: python1
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
