apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - args:
        - "100000"
        command:
        - sleep
        image: python
        name: python
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - "100000"
        command:
        - sleep
        image: python
        name: python1
        ports:
        - containerPort: 80
          protocol: TCP